import OpenAI from 'openai';

const NVIDIA_BASE_URL = 'https://integrate.api.nvidia.com/v1';

function getClient(): OpenAI {
    const apiKey = process.env.NVIDIA_API_KEY;
    if (!apiKey) throw new Error('NVIDIA_API_KEY environment variable is not set');
    return new OpenAI({
        apiKey,
        baseURL: NVIDIA_BASE_URL,
    });
}

const SYSTEM_PROMPT = `You are a senior infrastructure and security engineer writing detailed technical documentation.

Write your response entirely in valid Markdown format. Do not wrap everything in a JSON object.

Your document must strictly follow this structure:
# [The exact topic title]

> **Category:** [Category Name]
> **Generated:** [YYYY-MM-DD]
> **AI Model:** Kimi K2.5 via NVIDIA NIM

---

## Overview
2-3 paragraphs explaining the concept at an intermediate-to-advanced level. No fluff. No "in today's world" intro. Start with the technical substance.

## Architecture
Detailed architectural explanation. Describe components, data flows, decision points, and interactions.

### Architecture Diagram
[Insert a relevant Mermaid.js diagram using graph TD or sequenceDiagram format inside a \`\`\`mermaid block]

## Implementation Details
Concrete implementation guidance. Include configuration examples, code snippets, CLI commands, or protocol-level details.

## Misconfigurations & Edge Cases
Common mistakes engineers make. Describe specific misconfigurations, their impact, and how to detect/fix them.

## Best Practices
Production-grade best practices. Be specific.

## Real-World Context
How this applies in real production environments. Reference real-world incidents, common scenarios, or industry patterns.

## Key Takeaways
- [5-7 concise technical takeaways as a bulleted list]

---
*This document was generated by the Autonomous Technical Knowledge Publisher (ATKP) — an AI-driven publishing engine for structured engineering documentation.*

Rules:
- Write at intermediate-to-advanced engineer level.
- No marketing language. No fluff. Be technically precise.
- The total content should be substantial — at least 1500 words equivalent.
- Return ONLY the formatted Markdown.`;

/**
 * Streams the generated article directly to the client as Markdown chunks.
 * Upon completion, it calls `onComplete` with the final compiled Markdown string 
 * so the server can commit it to GitHub before closing the stream.
 */
export async function generateArticleStream(
    topic: string,
    category: string,
    onComplete: (content: string) => Promise<{ commitSha: string } | { error: string }>
): Promise<ReadableStream> {
    const client = getClient();
    const date = new Date().toISOString().split('T')[0];

    // Pre-fill parameters for the AI
    const systemPromptWithDate = SYSTEM_PROMPT.replace('[YYYY-MM-DD]', date).replace('[Category Name]', category);

    const userPrompt = `Write a comprehensive technical document about: "${topic}"
Category: ${category}

Produce a deep, engineering-grade analysis reading like internal documentation at a top-tier tech company.`;

    const response = await client.chat.completions.create({
        model: 'moonshotai/kimi-k2.5',
        messages: [
            { role: 'system', content: systemPromptWithDate },
            { role: 'user', content: userPrompt },
        ],
        temperature: 1.00,
        top_p: 1.00,
        max_tokens: 16384,
        stream: true, // We are streamig!
    });

    return new ReadableStream({
        async start(controller) {
            let fullContent = '';
            try {
                for await (const chunk of response) {
                    const content = chunk.choices[0]?.delta?.content || '';
                    if (content) {
                        fullContent += content;
                        controller.enqueue(new TextEncoder().encode(content));
                    }
                }

                // Stream finished. Now run the commit logic in the background before closing.
                controller.enqueue(new TextEncoder().encode('\n\n--- *Committing to GitHub...* ---\n'));

                const result = await onComplete(fullContent);

                if ('commitSha' in result) {
                    controller.enqueue(new TextEncoder().encode('\n\n[ATKP_SUCCESS: ' + result.commitSha + ']'));
                } else {
                    controller.enqueue(new TextEncoder().encode('\n\n[ATKP_ERROR: ' + result.error + ']'));
                }

            } catch (err) {
                console.error('Streaming generation error:', err);
                controller.enqueue(new TextEncoder().encode('\n\n[ATKP_ERROR: AI Stream failed]'));
            } finally {
                controller.close();
            }
        },
    });
}
